version: 2
formats: [html]
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Note that this HTML won't be automatically uploaded,
      # unless your documentation build includes it somehow.
      - doxygen